services:
  app:
    build: .
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor # This prevents the host from overwriting the container's vendor folder
    networks:
      - slim-network

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - slim-network

networks:
  slim-network:
    driver: bridge
