#!/usr/bin/env php
<?php

require __DIR__ . '/config/bootstrap.php';

use Symfony\Component\Console\Application;

$application = new Application('Slim API Starter', 'v1.0');

// ... register commands
$application->addCommand(new \App\Commands\MakeActionCommand());

exit($application->run());
