#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$settings = require __DIR__.'/config/settings.php';
$appSettings = $settings['settings'];

require __DIR__.'/config/bootstrap.php';

use App\Commands\LogsClearCommand;
use App\Commands\MakeActionCommand;
use App\Commands\MakeMigrationCommand;
use App\Commands\MakeModelCommand;
use App\Commands\MigrateCommand;
use App\Commands\MigrationRollbackCommand;
use App\Commands\SeedCreateCommand;
use App\Commands\SeedRunCommand;
use Symfony\Component\Console\Application;

$application = new Application($appSettings['app_name'], $appSettings['app_version']);

// register commands
$application->addCommands([
    new LogsClearCommand,
    new MakeActionCommand,
    new MakeModelCommand,
    new MakeMigrationCommand,
    new MigrateCommand,
    new MigrationRollbackCommand,
    new SeedCreateCommand,
    new SeedRunCommand,
]);

exit($application->run());
