#!/usr/bin/env php
<?php

require __DIR__.'/config/bootstrap.php';

use App\Commands\LogsClearCommand;
use App\Commands\MakeActionCommand;
use App\Commands\MakeMigrationCommand;
use App\Commands\MakeModelCommand;
use App\Commands\SeedCreateCommand;
use App\Commands\SeedRunCommand;
use Symfony\Component\Console\Application;

$application = new Application('Slim API Starter', 'v1.0');

// register commands
$application->addCommands([
    new LogsClearCommand,
    new MakeActionCommand,
    new MakeModelCommand,
    new MakeMigrationCommand,
    new SeedCreateCommand,
    new SeedRunCommand,
]);

exit($application->run());
